# Generated by Django 4.1.2 on 2022-11-01 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryCatalog', '0003_remove_author_date_of_death_book_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='isbn',
            field=models.CharField(default=1234567891234, max_length=13, unique=True, verbose_name='ISBN'),
            preserve_default=False,
        ),
    ]
