# Generated by Django 4.1.2 on 2022-11-01 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryCatalog', '0005_alter_bookinstance_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
    ]
