# Generated by Django 4.1.2 on 2022-11-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryCatalog', '0006_remove_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='instances', to='LibraryCatalog.book'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'ON LOAN'), ('h', 'ON HOLD'), ('a', 'AVAILABLE'), ('u', 'UNAVAILABLE'), ('r', 'HOLD REQUESTED')], default='u', help_text='Current Book Status', max_length=1),
        ),
    ]
