# Generated by Django 4.1.2 on 2022-11-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryCatalog', '0008_bookinstance_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='hold_status',
            field=models.CharField(blank=True, choices=[('n', 'NO HOLDS'), ('r', 'HOLD REQUESTED'), ('h', 'ON HOLD')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'ON LOAN'), ('h', 'ON HOLD'), ('a', 'AVAILABLE'), ('u', 'UNAVAILABLE')], default='a', help_text='Current Book Status', max_length=1),
        ),
    ]
