# Generated by Django 4.1.2 on 2022-11-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryCatalog', '0009_bookinstance_hold_status_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='labelID',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
    ]
