# Generated by Django 4.1.2 on 2022-11-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryCatalog', '0010_bookinstance_labelid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='labelID',
            new_name='labelId',
        ),
    ]
