# Generated by Django 4.1.2 on 2022-12-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryCatalog', '0014_bookinstance_holder'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookinstance',
            index=models.Index(fields=['labelId'], name='LibraryCata_labelId_cb08bd_idx'),
        ),
    ]
